# Wirepas Oy
#

version: '3'
services:

    wm-sink:
        container_name: wm-sink
        image: wm-lxgw:latest
        build:
            context: .
            dockerfile: Dockerfile-rpi

        user: root
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - wm_gateway.env

        volumes:
            - /dev:/dev
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

        logging:
           driver: journald

        command: sink

    wm-transport:
        container_name: wm-transport
        image: wm-lxgw:latest
        build:
            context: .
            dockerfile: Dockerfile-rpi

        user: root
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - wm_gateway.env

        volumes:
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

        logging:
            driver: journald

        command: transport

    # in the future we would like to add a dbus container, to allow
    # the gateway to run anywhere where docker engine is available
    # now it relies on the host dbus to be running - thus also
    # a major security concern
    #wm-bus: