FROM python:3.7.7-buster

RUN useradd -ms /bin/bash wirepas
RUN apt-get update

RUN apt-get install -y \
	python3-dev \
        python3-gi \
        libsystemd-dev \
        libgirepository1.0-dev

USER wirepas

RUN python3 -m pip install --no-cache-dir --upgrade pip \
    && python3 -m pip install wheel setuptools

RUN pip3 install PyGObject --user
