name: build dbus image

on:
  push:
    branches: docker_rework
    paths:
    - 'docker/transport_service/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build image
        run: |
          docker buildx build --target transport_builder_base --push \
          --tag gwendalraoul/transport_builder_base:latest \
          --platform linux/amd64,linux/arm -f docker/transport_service/Dockerfile .
          
