name: build dbus image

on:
  push:
    branches: docker_rework
    paths:
    - 'docker/dbus/**'
    - 'sink_service/com.wirepas.sink.conf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the dbus image
        run: |
          docker buildx build --push \
          --tag gwendalraoul/dbus:v0.1 \
          --platform linux/amd64,linux/arm -f docker/dbus/Dockerfile .
          
