name: build transport base builder

on:
  push:
    branches: docker_rework
    paths:
    - 'docker/transport_service/Dockerfile_base_builder'
    - '.github/workflows/docker_transport_base_builder.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build image
        run: |
          docker buildx build --push \
          --tag gwendalraoul/transport_base_builder:latest \
          --platform linux/amd64,linux/arm -f docker/transport_service/Dockerfile_base_builder .
          
